
[[operation]]
Name = "Extract Archives"
Instructions = "run quickbms script using RemakeRegistry/Games/Simpsons-Hit-and-Run/Scripts/atg_core_cement.bms"
script_type = "bms"
script = "{{Game_Root}}/Scripts/atg_core_cement.bms"
input = "{{SourcePath}}"
output = "GameFiles/STROUT"
extension = ".str"


